name: aarnet_filesender
owner: galaxy-australia
homepage_url: https://filesender.aarnet.edu.au
remote_repository_url: https://github.com/usegalaxy-au/tools-au/tree/master/tools/aarnetfilesender
categories:
  - Data Export
type: unrestricted
description: Transfer files to AARNet's FileSender Service
long_description: Transfer files to AARNet's FileSender Service
include:
  - filesender.xml
  - macros.xml
  - test-data
