name: pbmm2
owner: iuc
description: Compute genomic consensus and call variants using PacBio reads mapped to a reference.
homepage_url: https://github.com/PacificBiosciences/pbmm2
long_description: |
    Compute genomic consensus and call variants using PacBio reads mapped to a reference 
remote_repository_url: https://github.com/usegalaxy-au/galaxy-local-tools/tree/master/tools/pbmm2
type: unrestricted
categories:
- Assembly
