name: pbmm2
owner: iuc
description: A minimap2 SMRT wrapper for PacBio data: native PacBio data in ⇨ native PacBio BAM out.
homepage_url: https://github.com/PacificBiosciences/pbmm2
long_description: |
    A minimap2 SMRT wrapper for PacBio data: native PacBio data in to native PacBio BAM out.
remote_repository_url: https://github.com/usegalaxy-au/galaxy-local-tools/tree/master/tools/pbmm2
type: unrestricted
categories:
- Assembly
