---
name: Galaxy Tool Linting and Tests for push and PR
on: [pull_request]
env:
  GALAXY_FORK: galaxyproject
  GALAXY_BRANCH: release_22.05
  MAX_CHUNKS: 4
  MAX_FILE_SIZE: 1M
jobs:
  call-tools-iuc-pr-workflow:
    uses: tomharrop/tools-iuc/.github/workflows/pr.yaml@8402a2c4832669f18b633f0a7103087d513bfdf4